include 'internship'
include 'student_naidanov_p'
include 'student_khamit_bilyaletdinov'
include 'student_morozov_nikita'
include 'student_lesha_yurovskikh'
include 'student_konstantins_sevcenko'
include 'student_dmitrijs_baumanis'
include 'student_stanislav_gritsenko'
include 'student_armens_brutjans'
include 'student_yuriy_k'
include 'student_oleg_oskar'
include 'student_korolev_pasha'
include 'student_eugene_ivaschenko'
include 'student_konovalova_alina'
include 'student_vladislavs_katirlovs'
include 'student_dmitrijs_anosovs'
include 'student_timonin_andrey'
include 'student_olesja_c'
include 'student_andrejs_tripuks'
include 'student_alexander_keda'
include 'student_oleg_ganisevsky'
include 'student_stanislav_popkov'
include 'student_igors_anastasjevs'
include 'student_mikhailov_danil'
include 'student_aleksandr_komarov'
include 'student_vlasov_maksim'

